# Generated by Django 4.2.10 on 2024-03-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_carouselimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carouselimage",
            name="image",
            field=models.ImageField(upload_to="static/images/carousel"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="static/images/products"
            ),
        ),
    ]
