# Generated by Django 4.2.10 on 2024-03-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
