# Generated by Django 4.2.10 on 2024-03-11 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_cart"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
