# Generated by Django 4.2.10 on 2024-03-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
