# Generated by Django 4.2.10 on 2024-03-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Delivered", "Delivered"),
                    ("Not Delivered", "Not Delivered"),
                ],
                default="Not Delivered",
                max_length=20,
            ),
        ),
    ]
